name: Branch Name

on:
    push:
        branches:
            - main

jobs:
    print_branch_name:
        runs-on: ubuntu-latest
        steps:
            - name: Print Branch Name
              env:
                BRANCH_NAME: ${{github.ref}}
              run: |
               echo "Branch Name: ${{github.ref}}"